#pragma config(Sensor, dgtl12, green,          sensorLEDtoVCC)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           LeftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           servoMotor,    tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	turnLEDOff(green);
	wait(1);
	turnLEDOn(green);
	wait(1);
	turnLEDOff(green);
	wait(1);
	turnLEDOn(green);
	wait(1);
	turnLEDOff(green);



}
