#pragma config(Sensor, in1,    lineFollower,   sensorLineFollower)
#pragma config(Sensor, in3,    lightSensor,    sensorReflection)
#pragma config(Sensor, dgtl2,  bumpSwitch,     sensorTouch)
#pragma config(Sensor, dgtl5,  sonar,          sensorSONAR_cm)
#pragma config(Sensor, dgtl12, Red,            sensorNone)
#pragma config(Motor,  port1,           flashlight1,   tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           hookMotor1,    tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port10,          flashlight2,   tmotorVexFlashlight, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	//while(1 == 1)

	//wait1Msec(5);
	startMotor(leftMotor, 127);        //truck goes in reverse
	startMotor(rightMotor, 127);       //truck goes in reverse

	//untilSonarLessThan(20, sonar);
	//{
	//	startMotor(leftMotor, 0);
	//	startMotor(rightMotor, 0);
	//}

	untilSonarLessThan(20, sonar);    //truck stops when object is sensed
	stopMotor(leftMotor);             //the motors stop
	stopMotor(rightMotor);            //the motors stop
	wait(2);


	startMotor(hookMotor1, - 25);      //the hook lowers
	wait(7);
	stopMotor(hookMotor1);            //waits 2 seconds before the hook stops lowering
	wait(8);                          //the hook is attached
	startMotor(hookMotor1, -25);       //the hook goes back up
	wait(6);
	stopMotor(hookMotor1);            //the hook will stop
	wait(5);
	startMotor(leftMotor, -50);       //the trucks motors will go forward
	startMotor(rightMotor, -50);      //the trucks motors will go forward
	wait(4);
	stopMotor(leftMotor);
	stopMotor(rightMotor);
	wait(4);
	startMotor(hookMotor1, 25);
	wait(7);
	stopMotor(hookMotor1);
	wait(8);
	startMotor(hookMotor1, -25);
	wait(6);
	stopMotor(hookMotor1);
	wait(5);
	startMotor(leftMotor, -50);       //the trucks motors will go forward
	startMotor(rightMotor, -50);

	//while(1 == 1)
	//{
	//	if (SensorValue(lightSensor)>700)      //some magic happens
	//	{
	//		turnFlashlightOn(flashlight1, 127);  //turns flashlight on
	//	}
	//	if (SensorValue(lightSensor) <= 700)   //magic happens again
	//	{
	//		turnFlashlightOff(flashlight1);      //turns flashlight off
	//	}
	//}
}
